services:
  postgres:
    image: postgres:latest
    container_name: postgres_forum
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend_forum
    restart: always
    depends_on:
      - postgres
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      JWKS_URL: ${JWKS_URL}
    ports:
      - "3003:3003"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: frontend_forum
    restart: always
    depends_on:
      - backend
    ports:
      - "8282:80"
    volumes:
      - ./frontend/app:/usr/share/nginx/html

volumes:
  postgres_data:
